name: Generate Snake Animation

on:
  schedule:
    # Run automatically every 12 hours
    - cron: "0 */12 * * *"
  
  # Allows manual triggering via the Actions tab
  workflow_dispatch:
  
  # Run on every push to main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2358A6FF&color_dots=%23161b22,%230d3868,%231f6feb,%23388bfd,%2358a6ff
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFB000&color_dots=%23161b22,%230d3868,%231f6feb,%23388bfd,%2358a6ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
